apiVersion: v1
kind: Service
metadata:
  name: {{ include "openmrs-helm.fullname" . }}
  labels:
    {{- include "openmrs-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
  clusterIP: None
  selector:
    {{- include "openmrs-helm.selectorLabels" . | nindent 4 }}